export const subjects = [
  {
    code: '9701',
    name: 'Chemistry',
    slug: 'chemistry',
    description: 'Organic, physical, and inorganic chemistry topics aligned to the Cambridge AS & A Level syllabus.',
  },
  {
    code: '9702',
    name: 'Physics',
    slug: 'physics',
    description: 'Mechanics, electricity, waves, and modern physics topics indexed for fast retrieval.',
  },
  {
    code: '9709',
    name: 'Mathematics',
    slug: 'mathematics',
    description: 'Pure mathematics, mechanics, and probability & statistics topics mapped by paper and series.',
  },
] as const;

export const topicGroups = [
  {
    subjectSlug: 'chemistry',
    topic: 'Atomic structure',
    subtopics: ['Atoms', 'Electron structure'],
    questionCount: 92,
  },
  {
    subjectSlug: 'chemistry',
    topic: 'Energetics',
    subtopics: ['Enthalpy', 'Bond energies'],
    questionCount: 48,
  },
  {
    subjectSlug: 'physics',
    topic: 'Mechanics',
    subtopics: ['Kinematics', 'Forces'],
    questionCount: 114,
  },
  {
    subjectSlug: 'physics',
    topic: 'Electricity',
    subtopics: ['Current', 'Resistance'],
    questionCount: 78,
  },
  {
    subjectSlug: 'mathematics',
    topic: 'Functions',
    subtopics: ['Transformations', 'Inverse functions'],
    questionCount: 126,
  },
  {
    subjectSlug: 'mathematics',
    topic: 'Probability',
    subtopics: ['Discrete distributions', 'Conditional probability'],
    questionCount: 83,
  },
] as const;

export const questionRecords = [
  {
    id: 'chem-1',
    subject: 'Chemistry',
    subjectSlug: 'chemistry',
    topic: 'Atomic structure',
    subtopic: 'Atoms',
    year: 2024,
    session: 'May/June',
    paper: 'P1',
    variant: '11',
    questionNumber: 5,
    marks: 10,
  },
  {
    id: 'chem-2',
    subject: 'Chemistry',
    subjectSlug: 'chemistry',
    topic: 'Energetics',
    subtopic: 'Enthalpy',
    year: 2023,
    session: 'October/November',
    paper: 'P2',
    variant: '12',
    questionNumber: 9,
    marks: 12,
  },
  {
    id: 'chem-3',
    subject: 'Chemistry',
    subjectSlug: 'chemistry',
    topic: 'Atomic structure',
    subtopic: 'Electron structure',
    year: 2022,
    session: 'February/March',
    paper: 'P3',
    variant: '13',
    questionNumber: 3,
    marks: 8,
  },
  {
    id: 'phys-1',
    subject: 'Physics',
    subjectSlug: 'physics',
    topic: 'Mechanics',
    subtopic: 'Kinematics',
    year: 2024,
    session: 'May/June',
    paper: 'P1',
    variant: '21',
    questionNumber: 7,
    marks: 9,
  },
  {
    id: 'phys-2',
    subject: 'Physics',
    subjectSlug: 'physics',
    topic: 'Electricity',
    subtopic: 'Current',
    year: 2024,
    session: 'October/November',
    paper: 'P4',
    variant: '22',
    questionNumber: 4,
    marks: 14,
  },
  {
    id: 'math-1',
    subject: 'Mathematics',
    subjectSlug: 'mathematics',
    topic: 'Functions',
    subtopic: 'Transformations',
    year: 2025,
    session: 'May/June',
    paper: 'P1',
    variant: '31',
    questionNumber: 1,
    marks: 15,
  },
  {
    id: 'math-2',
    subject: 'Mathematics',
    subjectSlug: 'mathematics',
    topic: 'Probability',
    subtopic: 'Conditional probability',
    year: 2024,
    session: 'February/March',
    paper: 'P5',
    variant: '32',
    questionNumber: 12,
    marks: 6,
  },
] as const;
